# action.yml
name: 'Image Resizer Inplace Idempotent'
description: 'Resize images in place, keeping aspect ratio, but only when image width or height exceeds the given max width or height'
branding:
  icon: 'image'  
  color: 'green'
inputs:
  target:
    description: 'Folder in which images are stored'
    required: true
    default: 'images'
  width:
    description: 'Max width for images'
    required: true
    default: 500
  height:
    description: 'Max height for images'
    required: true
    default: 9999
outputs:
  time:
    description: 'The time we greeted you'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
    - ${{ inputs.width }}
    - ${{ inputs.height }}
